# Generated by Django 4.1.7 on 2023-03-14 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='items',
            field=models.ManyToManyField(to='users.menuitem'),
        ),
        migrations.AlterField(
            model_name='bag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
