# Generated by Django 4.1.7 on 2023-03-14 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_bag_items_alter_bag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='quantity_type',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Bag',
        ),
    ]
