# Generated by Django 4.1.7 on 2023-03-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_menuitem_quantity_type_delete_bag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='quantity_type',
            field=models.CharField(default="Kg's", max_length=100),
        ),
    ]
