# Generated by Django 4.1.7 on 2023-03-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_droppeditem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DroppedItem',
        ),
    ]
