# Generated by Django 4.2 on 2023-04-12 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_delivary_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription_details',
            name='area_street',
        ),
        migrations.RemoveField(
            model_name='subscription_details',
            name='city',
        ),
        migrations.RemoveField(
            model_name='subscription_details',
            name='flat_house_no',
        ),
        migrations.RemoveField(
            model_name='subscription_details',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='subscription_details',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='subscription_details',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='subscription_details',
            name='name',
        ),
        migrations.RemoveField(
            model_name='subscription_details',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='subscription_details',
            name='state',
        ),
        migrations.AddField(
            model_name='subscription_details',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.delivary_address'),
            preserve_default=False,
        ),
    ]
