# Generated by Django 4.2 on 2023-04-12 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_subscription_details_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription_details',
            name='default',
        ),
    ]
